### PR TITLE
Set chunksSortMode to 'dependency'

### PR DESCRIPTION
**Pull request by watrool**
Connected to https://github.com/rangle/rangle-starter/issues/193

### CODE REVIEW

**Comment by winkerVSbecks** [comment]
@watrool the e2e tests are failing for this because we no longer have the app (login/counter) to test. You should probably delete the e2e tests.

**Comment by winkerVSbecks** [comment]
Should we stay consistent and have a similar `circle.yml` file to what the angular2 starter has https://github.com/rangle/angular2-starter/blob/master/circle.yml ?

**Comment by watrool** [comment]
@winkerVSbecks Yes, I plan to do that here: https://github.com/rangle/react-starter/pull/2 after this gets merged, I will rebase #2 and change it to yarn.

**Comment by winkerVSbecks** [comment]
:shipit:

**Pull request merged**
